site_name: RocketMod Documentation
copyright: 'RocketMod is licensed under <a href="https://creativecommons.org/licenses/by-nc-nd/4.0/">CC BY-NC-ND 4.0</a><br>This documentation is licensed under <a href="http://creativecommons.org/licenses/by-sa/3.0/">CC BY-SA 3.0</a>'
docs_dir: 'content'
repo_name: 'RocketMod/Rocket'
repo_url: 'https://github.com/RocketMod/Rocket'
edit_uri: 'edit/rework/docs/content/'
pages:
    - Home: index.md
    - User Guide:
        - Installation:
            - Unturned 3: user-guide/installation/unturned3.md
            - Eco: user-guide/installation/eco.md
        - Configuration: 
            - Configurations: user-guide/configuration/configurations.md
            - Translations: user-guide/configuration/translations.md
            - Permissions: user-guide/configuration/permissions.md
            - Plugins: user-guide/configuration/plugins.md
        - Plugins: 
            - Installation: user-guide/plugins/installation.md
        - Support: user-guide/support.md
    - Development Guide:
        - Concept:
            - Coding Style: development-guide/coding-style.md
            - Documentation: development-guide/documentation.md
            - Patterns:
                - Inversion Of Control: development-guide/ioc.md
            - Compatibility: development-guide/compatibility.md
        - API:
            - Database: development-guide/api/database.md
        - Core Implementation:
            - List of all Services: development-guide/core-implementation/services.md
            - Eventing: development-guide/core-implementation/eventing.md
            - Permissions: development-guide/core-implementation/permissions.md
            - Logging: development-guide/core-implementation/logging.md
        - Plugins:
            - Migration Guide: development-guide/plugins/migration-guide.md
        - Game Implementations:
            - Creating a new implementation: development-guide/game-implementations/creating-a-new-implementation.md
            - Unturned 3:
                - Home : development-guide/game-implementations/unturned3/index.md
            - Eco:
                - Home : development-guide/game-implementations/eco/index.md
    - About:
        - Licensing: about/licensing.md
        - Contributors: about/contributors.md

theme:
  custom_dir: 'theme'
  name: 'material'
  palette:
    primary: 'cyan'
    accent: 'light blue'
  logo: 'images/rocket.svg' 
  language: 'en'
  feature:
    tabs: true
markdown_extensions:
  - admonition
  - meta
  - codehilite:
      guess_lang: true
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde